### ISSUE TITLE
希望能更新适配到swift4.0 

### ISSUE THREAD

**Issue by yihaodevelop** [jpush/jchat-swift#14]
请问是否有计划源码适配swift4.0呢？

**Comment by Eonlychen** [comment]
在swift4.1中， Method 'initialize()' defines Objective-C class method 'initialize', which is not permitted by Swift 已经报错了，同楼上问

**Comment by Rubyios** [comment]
这代码 太鸡吧老了

**Comment by Rubyios** [comment]
该快升级吧 Xcode都不支持swift3.0了

**Comment by hyhSuper** [comment]
已更新。
