### ISSUE TITLE
JMUIMultiSelectPhotosKit(JMUIMultiSelectPhotosKit_vers.o)) was built for newer iOS version (9.2) than being linked (8.0)

### ISSUE THREAD

**Issue by charsunny** [jpush/jchat-swift#2]
JMUIMultiSelectPhotosKit(JMUIMultiSelectPhotosKit_vers.o)) was built for newer iOS version (9.2) than being linked (8.0)
please change build target of JMUIMultiSelectPhotosKit

**Comment by huangminlinux** [comment]
I had fix it in dev branch which will mergin to master branch in next release version.
