### ISSUE TITLE
能跑起来？

### ISSUE THREAD

**Issue by UninhibitedSoul** [jpush/jchat-swift#22]
能简单的跑起来？-(笑: library not found for -libstdc++.6.0.9 
跑个demo 也是不容易 rx 适合用来做demo吗？ 
打扰了

**Comment by runryan** [comment]
同样的问题

**Comment by equalriver** [comment]
已经放弃治疗了吧，还是swift 3的版本

**Comment by jettangtzj** [comment]
专门下载一个就是了啊，不是什么私有库

**Comment by zengxiang** [comment]
彻底GG了  3.0  搞鸡毛

**Comment by hyhSuper** [comment]
已更新到swift5.0
