### ISSUE TITLE
JCChatViewLayout  里面布局  写得太复杂 看不懂

### ISSUE THREAD

**Issue by zhulmin** [jpush/jchat-swift#7]
复杂界面里面不能使用autolayout，否则的话性能会很差，这个你可以直接套用，建议多看几次应该就没有问题的了

**Comment by huangminlinux** [comment]
https://github.com/jpush/aurora-imui

**Comment by zhulmin** [comment]
thank ~

**Comment by dengyhgit** [comment]
这里出于性能的考虑，聊天界面的内容都是手动布局
