### ISSUE TITLE
不知道为什么编译不起来，而且很卡

### ISSUE THREAD

**Issue by xiaobing1024** [jpush/jchat-swift#8]
不知道为什么编译不起来，进度条停在那边，让电脑都很卡

**Comment by xiaobing1024** [comment]
电脑太卡，截图不能提供了，xcode是8.2.1

**Comment by dengyhgit** [comment]
你可以根据readme里面的步骤来做

**Comment by dengyhgit** [comment]
@xiaobing1024 这个问题升级xcode 到最新版本就可以解决了，不属于代码层的问题
